### ISSUE TITLE
Elasticsearch: self signed certs and authentication

### ISSUE THREAD

**Issue by Cobra1978** [mhilker/cspr-collector#6]
Hi.

Is possible to have support for connecting an external elasticsearch witt self signed https certs and user/password authentication?

**Comment by mhilker** [comment]
This should be possible. Let me look into it.

**Comment by mhilker** [comment]
I have added the `-output-es-ca-file`, `-output-es-cert-file`, and `-output-es-key-file` options for certificates for elasticsearch on master. Are you willing to give it a try?

**Comment by Cobra1978** [comment]
Yess, i will give it a try in the next days, thanks!

**Comment by Cobra1978** [comment]
Just a little question: what is the need to configure even the certificate and the key?

Isn't enough the root ca to let the csp collector recognize the cert on the elasticsearch server?

**Comment by mhilker** [comment]
> Just a little question: what is the need to configure even the certificate and the key?
> Isn't enough the root ca to let the csp collector recognize the cert on the elasticsearch server?

You have to use the options if you want to use a client certificate for authentication. When you just want to use TLS + Basic Auth for example, the Elasticsearch Url `https://user:password@elasticsearch.example.com:443` **should** be enough.

> Have you updated even the docker image on dockerhub? I'm using your software on docker.

No, currently the change is only on the master branch on github. I will update the docker image soon.

**Comment by mhilker** [comment]
> Have you updated even the docker image on dockerhub? I'm using your software on docker.

The image is now updated.

**Comment by Cobra1978** [comment]
Perfect, thanks, i will try it as soon as possible ;)

**Comment by Cobra1978** [comment]
I can confirm that the flag -output-es-ca-file works perfectly.

I can't test the client certificates flags because we don'use client certificates.

Very thnaks and best regards.
